# Generated by Django 4.2.5 on 2023-09-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_Lesson_8', '0003_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ammount',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='package',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='recommendation',
            field=models.BooleanField(default=False),
        ),
    ]
